#!/bin/bash
let charos=0
cd Epitech
for name in *
do
	if [ "${name: -1}" != "z" ] && [ "${name: -1}" != "a" ]; then
		rm $name
	fi
done

cd ../ISEG
for  name in *
do
	if [ "${name: -1}" == "a" ]; then
		((charos+=1))
	elif [ "${name: -1}" != "z" ]; then
		rm $name
	fi
done
cd ..
exit $charos
